package ASCII

var SymbolsRelations = [][][]bool{
	{
		{true, true, true},
		{true, false, true},
		{true, true, true},
		{true, false, true},
		{true, false, true},
	},
	{
		{true, true, false},
		{true, false, true},
		{true, true, true},
		{true, false, true},
		{true, true, false},
	},
	{
		{true, true, true},
		{true, false, false},
		{true, false, false},
		{true, false, false},
		{true, true, true},
	},
	{
		{true, true, false},
		{true, false, true},
		{true, false, true},
		{true, false, true},
		{true, true, false},
	},
	{
		{true, true, true},
		{true, false, false},
		{true, true, true},
		{true, false, false},
		{true, true, true},
	},
	{
		{true, true, true},
		{true, false, false},
		{true, true, true},
		{true, false, false},
		{true, false, false},
	},
	{
		{false, true, true, false},
		{true, false, false, false},
		{true, false, true, true},
		{true, false, false, true},
		{false, true, true, false},
	},
	{
		{true, false, true},
		{true, false, true},
		{true, true, true},
		{true, false, true},
		{true, false, true},
	},
	{
		{false, true, false},
		{false, true, false},
		{false, true, false},
		{false, true, false},
		{false, true, false},
	},
	{
		{false, true, true},
		{false, false, true},
		{false, false, true},
		{false, false, true},
		{true, true, true},
	},
	{
		{true, false, true},
		{true, false, true},
		{true, true, false},
		{true, false, true},
		{true, false, true},
	},
	{
		{true, false, false},
		{true, false, false},
		{true, false, false},
		{true, false, false},
		{true, true, true},
	},
	{
		{true, false, false, false, true},
		{true, true, false, true, true},
		{true, true, true, true, true},
		{true, false, true, false, true},
		{true, false, false, false, true},
	},
	{
		{true, false, false, false, true},
		{true, true, false, false, true},
		{true, false, true, false, true},
		{true, false, false, true, true},
		{true, false, false, true, true},
	},
	{
		{false, true, false},
		{true, false, true},
		{true, false, true},
		{true, false, true},
		{false, true, false},
	},
	{
		{true, true, true, true, false},
		{true, false, false, false, true},
		{true, true, true, true, false},
		{true, false, false, false, false},
		{true, false, false, false, false},
	},
	{
		{false, true, false},
		{true, false, true},
		{true, false, true},
		{true, false, true},
		{false, true, true},
	},
	{
		{true, true, false},
		{true, false, true},
		{true, true, true},
		{true, false, true},
		{true, false, true},
	},
	{
		{true, true, true},
		{true, false, false},
		{true, true, true},
		{false, false, true},
		{true, true, true},
	},
	{
		{true, true, true},
		{false, true, false},
		{false, true, false},
		{false, true, false},
		{false, true, false},
	},
	{
		{true, false, true},
		{true, false, true},
		{true, false, true},
		{true, false, true},
		{true, true, true},
	},
	{
		{true, false, true},
		{true, false, true},
		{true, false, true},
		{true, true, true},
		{false, true, false},
	},
	{
		{true, false, true},
		{true, false, true},
		{true, false, true},
		{true, true, true},
		{true, false, true},
	},
	{
		{true, false, true},
		{true, false, true},
		{false, true, false},
		{true, false, true},
		{true, false, true},
	},
	{
		{true, false, true},
		{true, false, true},
		{false, true, true},
		{false, false, true},
		{true, true, true},
	},
	{
		{true, true, true},
		{false, false, true},
		{false, true, false},
		{true, false, false},
		{true, true, true},
	},
}

var SpecSymbols = []struct {
	ASCII_IX       uint8
	RelationMatrix [][]bool
}{
	{
		ASCII_IX: 32,
		RelationMatrix: [][]bool{
			{false, false},
			{false, false},
			{false, false},
			{false, false},
			{false, false},
		},
	},
}
